---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: kontinuous-ui
    type: dashboard
  name: kontinuous-ui
  namespace: acaleph
spec:
  ports:
  - name: dashboard
    port: 5000
    protocol: TCP
    targetPort: 8081
  selector:
    app: kontinuous
    type: dashboard

---
apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    app: kontinuous-ui
    type: dashboard
  name: kontinuous-ui
  namespace: acaleph
spec:
  replicas: 1
  selector:
    app: kontinuous-ui
    type: dashboard
  template:
    metadata:
      labels:
        app: kontinuous-ui
        type: dashboard
      name: kontinuous-ui
      namespace: acaleph
    spec:
      containers:
      - env:
        - name: AUTH0_CLIENT_ID
          value: 
        - name: AUTH0_DOMAIN
          value: 
        - name: KONTINUOUS_API_URL
          value: 
        image: quay.io/acaleph/kontinuous-ui:dashboard
        imagePullPolicy: Always
        name: kontinuous-ui
        ports:
        - containerPort: 5000
          name: dashboard
          protocol: TCP